services:
  thirdparty:
    container_name: thirdparty
    build: ./thirdpartymock
    hostname: thirdparty
    restart: unless-stopped
    ports:
      - '3000:3000'

  client:
    container_name: client
    build: ./client
    hostname: client
    restart: unless-stopped
    ports:
      - '3100:3100'
    environment:
      YOUR_API: ${YOUR_API-http://host.docker.internal:3200}

  your_api_consumer:
    container_name: your_api_consumer
    build:
      context: ./your_api
      dockerfile: Dockerfile.consumer
    hostname: your_api_consumer
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      TURBO_TELEMETRY_DISABLED: 1
      REDIS_HOSTNAME: ${REDIS_HOSTNAME-host.docker.internal}
      REDIS_PORT: ${REDIS_PORT-6379}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DATABASE: ${REDIS_DATABASE}
      REDIS_SENTINEL: ${REDIS_SENTINEL}
      DB_HOST: ${DB_HOST-host.docker.internal}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME-djamo}
      DB_SYNCHRONIZE: ${DB_SYNCHRONIZE}
      CORS_ORIGINS: ${CORS_ORIGINS-*}
      YOUR_API: ${YOUR_API-http://host.docker.internal:3200}
      THIRD_PARTY_API_URL: ${THIRD_PARTY_API_URL-http://host.docker.internal:3000}
      CLIENT_API_URL: ${CLIENT_API_URL-http://host.docker.internal:3100}

  your_api_producer:
    container_name: your_api_producer
    build:
      context: ./your_api
      dockerfile: Dockerfile.producer
    hostname: your_api_producer
    restart: unless-stopped
    ports:
      - '3200:3200'
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      TURBO_TELEMETRY_DISABLED: 1
      REDIS_HOSTNAME: ${REDIS_HOSTNAME-host.docker.internal}
      REDIS_PORT: ${REDIS_PORT-6379}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DATABASE: ${REDIS_DATABASE}
      REDIS_SENTINEL: ${REDIS_SENTINEL}
      DB_HOST: ${DB_HOST-host.docker.internal}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME-djamo}
      DB_SYNCHRONIZE: ${DB_SYNCHRONIZE}
      CORS_ORIGINS: ${CORS_ORIGINS-*}
      YOUR_API: ${YOUR_API-http://host.docker.internal:3200}
      THIRD_PARTY_API_URL: ${THIRD_PARTY_API_URL-http://host.docker.internal:3000}
      CLIENT_API_URL: ${CLIENT_API_URL-http://host.docker.internal:3100}
